services:
  - type: web
    name: mon-dashboard-api
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: STRAVA_CLIENT_ID
        sync: false
      - key: STRAVA_CLIENT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: BACKEND_URL
        sync: false
